# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_user_bundle:
    resource: "@FourChimpsUserBundle/Resources/config/routing.yml"
    prefix:   /

_article_bundle:
    resource: "@FourChimpsArticleBundle/Resources/config/routing.yml"
    prefix:   /

_admin_bundle:
    resource: "@FourChimpsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin