<?php

namespace FourChimps\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    function findMostRecent($count = 5)
    {
        return $this
            ->createQueryBuilder('a')
            ->addOrderBy('a.created', 'DESC')
            ->setMaxResults($count)
            ->getQuery()
            ->getResult();
    }

}