<?php

namespace FourChimps\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagGroupRepository extends EntityRepository
{
}
